### ISSUE TITLE
Crash on key value 1000111

### ISSUE THREAD

**Issue by nagendragd** [riscv-newop/riscv-newop#12]
I see a crash inside RV32.py when it encounters key '1000111'. See Python crash stack:

Traceback (most recent call last):
  File "test_with_dump_file.py", line 38, in <module>
    test_dump_file()
  File "test_with_dump_file.py", line 35, in test_dump_file
    DumpFileReader("I32_asm_test.dump")
  File "test_with_dump_file.py", line 27, in __init__
    decoded_str = rv.decodeHex(instruction_word)
  File "/home/UNT/ndg0068/rv_tools/riscv-newop/rvnewop/RV32.py", line 50, in decodeHex
    return self.decode(ba)
  File "/home/UNT/ndg0068/rv_tools/riscv-newop/rvnewop/RV32.py", line 53, in decode
    return self.instructionTable[RVFormatParser.getOpcode(ba)](ba)
KeyError: frozenbitarray('1000111')

**Comment by prydt** [comment]
![image](https://user-images.githubusercontent.com/19543889/86971495-e6a21c80-c136-11ea-985e-c7ac29564d53.png)
![image](https://user-images.githubusercontent.com/19543889/86971571-02a5be00-c137-11ea-879d-3c1c7e99a2e9.png)

It looks like the key 1000111 is only for F,D, and Q extensions which we do not support yet.

**Comment by nagendragd** [comment]
Aha ok.. Any way that we can report this as such and not crash?

**Comment by prydt** [comment]
Yea I'll invoke get() on the instructionTable with a default value which should not crash. 

Should I return an "empty" instruction or just print an error?

**Comment by nagendragd** [comment]
That sounds good..
